---
title: "CCUS"
format: html
editor: visual
---

```{r}
# files
library("readxl") # to read the xlsx files

uu <- read_excel("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/ghgp_data_2022.xlsx", 
                 sheet = "CO2 Injection", 
                 skip=3,
                 col_names = TRUE)

rr <- read_excel("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/ghgp_data_2022.xlsx", 
                 sheet = "Geologic Sequestration of CO2", 
                 skip=3,
                 col_names = TRUE)

seq <- rbind(subset(uu,select=c(1,5,9,10,12)),
             subset(rr,select=c(1,5,9,10,12)))
```

```{r}
write.csv(seq,"C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/seq.csv")
```

```{r}
library("googleway") 
library("ggmap")

key <- "AIzaSyCfFzakx2Ntztl6eGp3nHpvFa20rmw5xd0"
set_key(key)
register_google(key)

site <- seq[2,]
map <- get_googlemap(
  paste(site$Latitude,site$Longitude,sep=" "),
  maptype = "terrain",
  color = "bw",
  zoom=14
)
site$`Facility Id` <- as.character(site$`Facility Id`)
```

```{r}
ggmap(get_map(location=c(lon=-95.712891, lat=37.09024),
              zoom = 4,
              maptype = "terrain",
              color = "color"),
      extent = "device") +
  geom_point(data=seq,
             aes(x=Longitude,y=Latitude),
             color="black",
             size=2,
             shape=18) +
  theme(legend.position="none")

pie(table(seq$State),
    main="Carbon Capture Locations\n (States)")
```

```{r}
# transit related locations (police, firefighter, hospital, urgent care)

library("googleway")

lat <- site$Latitude
long <- site$Longitude
id <- site$`Facility Id`

loc <- c("doctor", "hospital", "church")

places <- data.frame(
    lat=integer(),
    long=integer(),
    type=character(),
    facilitiy=character()
  )


```

```{r}
library("ggplot2")
ggmap(
  get_map(
    location=c(site$Longitude,site$Latitude),
          zoom=7,
          scale="auto")
) +
  geom_point(
    data=place,
    aes(x=lng,y=lat),
    fill="black",
    size=1)
```

```{r}
library("readxl")
de <- read_xls("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/direct_emitters.xls",skip=5)
de <- subset(de,select=c(5,6,13))

library("dplyr")
library("tidyverse")
de_subpart <- subset(de,select=c(3)) %>% 
  separate_rows(SUBPARTS, convert = TRUE) %>%
  drop_na() %>% 
  count(SUBPARTS)
```

zip codes within a radius for census data

```{r}
zip <- data.frame(
  zipcode = numeric(),
  distance = numeric(),
  id = factor()
)

library("zipcodeR")

for (i in 1:nrow(seq)) {
  zip_hold <- search_radius(seq$Latitude[i],seq$Longitude[i],20)
  zip_hold$id <- seq$`Facility Id`[i]
    
  zip <- rbind(zip_hold,zip)
}
```

census stuff

**age**

```{r}
census <- readr::read_csv("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/ACSST5Y2022.S0101-Data.csv")
```

```{r}
cols <- grep("E", names(census), value = TRUE)
census <- census[,cols]
census <- census[,c(1:21)]

census <- census[-c(1),-c(1)]
census[, c(2:20)] <- sapply(census[, c(2:20)], as.numeric)

census$totalpop <- census$S0101_C01_001E
census$under5 <- census$S0101_C01_002E
census$`5to19` <- census$S0101_C01_003E + census$S0101_C01_004E + census$S0101_C01_005E 
census$`19to64` <- census$S0101_C01_006E + census$S0101_C01_007E +     census$S0101_C01_008E + census$S0101_C01_009E + census$S0101_C01_010E + census$S0101_C01_011E + census$S0101_C01_012E + census$S0101_C01_013E + census$S0101_C01_014E
census$`over64` <- census$S0101_C01_015E + census$S0101_C01_016E + census$S0101_C01_017E + census$S0101_C01_018E + census$S0101_C01_019E 

census <- subset(census,select=c(1,21,22,23,24,25))
```

```{r}
census$under5 <- census$under5/census$totalpop
census$`5to19` <- census$`5to19`/census$totalpop
census$`19to64` <- census$`19to64`/census$totalpop
census$over64 <- census$over64/census$totalpop

census$NAME <- substr(census$NAME, nchar(census$NAME)-4, nchar(census$NAME))
```

```{r}
library("dplyr")
age <- left_join(zip,census,by=c("zipcode"="NAME"))
pop <- subset(age,select=c(1,2))
age <- aggregate(cbind(totalpop, under5,`5to19`,`19to64`,over64) ~ id, data=age, FUN=mean, na.rm=TRUE)
```

*graphs*

```{r}
library("reshape")
library("data.table")
age <- melt(setDT(age),id.var="id")
```

```{r}
library("tidyverse")
library("hrbrthemes")
library("viridis")
library("ggplot2")

age %>%
  ggplot( aes(x=variable, y=value, fill=variable)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      axis.text.x = element_text(angle=45,hjust=.8),
      plot.title = element_text(size=11)
    ) +
    xlab("") +
   ggtitle("Distribution of Ages Among Facilities")
```

```{r}
ggplot(age, aes(x = "", y = value, fill = variable)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6) +
  ggtitle("Age")
```

**income**

```{r}
census <- readr::read_csv("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/ACSST5Y2022.S1901-Data.csv")
```

```{r}
cols <- grep("E", names(census), value = TRUE)
census <- census[,cols]
census <- census[,c(1:14)]

census <- census[-c(1),-c(1)]
census[, c(2:13)] <- sapply(census[, c(2:13)], as.numeric)

census$totalpop <- census$S1901_C01_001E
census$income_median <- census$S1901_C01_012E
census$less25 <- census$S1901_C01_002E + census$S1901_C01_003E + census$S1901_C01_004E
census$`25to50` <- census$S1901_C01_005E + census$S1901_C01_006E
census$`50to75` <- census$S1901_C01_007E
census$`75to99` <- census$S1901_C01_008E
census$`100to150` <- census$S1901_C01_009E
census$`150to200` <- census$S1901_C01_010E
census$morethan200 <- census$S1901_C01_011E

census <- subset(census,select=c(1,14,15,16,17,18,19,20,21,22))

census$NAME <- substr(census$NAME, nchar(census$NAME)-4, nchar(census$NAME))

library("dplyr")
income <- left_join(zip,census,by=c("zipcode"="NAME"))
income_median <- subset(income,select=c(1,3,4))
income <- aggregate(cbind(totalpop, less25,`25to50`,`50to75`,`75to99`,`100to150`,`150to200`,morethan200) ~ id, data=income, FUN=mean, na.rm=TRUE)
```

*graph*

```{r}
library("reshape")
library("data.table")
income <- melt(setDT(income),id.var="id")

library("tidyverse")
library("hrbrthemes")
library("viridis")
library("ggplot2")

income %>%
  ggplot( aes(x=variable, y=value, fill=variable)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      axis.text.x = element_text(angle=45,hjust=.8),
      plot.title = element_text(size=11)
    ) +
    xlab("") +
   ggtitle("Distribution of Incomes")

income_median %>%
  ggplot( aes(x='',y=income_median)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      axis.text.x = element_text(angle=45,hjust=.8),
      plot.title = element_text(size=11)
    ) +
    xlab("") +
   ggtitle("Median Incomes")

```

**race and ethnicity**

```{r}
census <- readr::read_csv("C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/ACSDT5Y2022.B02001-Data.csv")

cols <- grep("E", names(census), value = TRUE)
census <- census[,cols]

census <- census[-c(1),-c(1)]

census$totalpop <- census$B02001_001E
census$white <- census$B02001_002E
census$black <- census$B02001_003E
census$native <- census$B02001_004E
census$asian <- census$B02001_005E
census$pacific <- census$B02001_006E
census$other <- census$B02001_007E
census$multiple <- census$B02001_008E

census <- subset(census,select=c(1,12,13,14,15,16,17,18,19))
census[, c(2:9)] <- sapply(census[, c(2:9)], as.numeric)

census$white <- census$white/census$totalpop
census$black <- census$black/census$totalpop
census$native <- census$native/census$totalpop
census$asian <- census$asian/census$totalpop
census$pacific <- census$pacific/census$totalpop
census$other <- census$other/census$totalpop
census$multiple <- census$multiple/census$totalpop

census$NAME <- substr(census$NAME, nchar(census$NAME)-4, nchar(census$NAME))

library("dplyr")
race <- left_join(zip,census,by=c("zipcode"="NAME"))
race <- aggregate(cbind(totalpop,white,black,native,asian,pacific,other,multiple) ~ id, data=race, FUN=mean, na.rm=TRUE)
```

*graph*

```{r}
library("reshape")
library("data.table")
race <- melt(setDT(race),id.var="id")

library("tidyverse")
library("hrbrthemes")
library("viridis")
library("ggplot2")

race %>%
  ggplot( aes(x=variable, y=value, fill=variable)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      axis.text.x = element_text(angle=45,hjust=.8),
      plot.title = element_text(size=11)
    ) +
    xlab("") +
   ggtitle("Distribution of Race/Ethnicity")
```

```{r}
write.csv(zip,"C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/zip.csv")
write.csv(age,"C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/age.csv")
write.csv(income,"C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/income.csv")
write.csv(race,"C:/Users/Emily/OneDrive/Documents/GitHub/24-fall-EFUGH/Fugh_Capstone/data/race.csv")
```
